#!/usr/bin/env bash

rg --line-number --no-heading --color=always --smart-case "$@" | fzf -d ':' -n 2.. --ansi --no-sort --preview-window 'top:60%:+{2}-/2' --preview 'bat --style=numbers --color=always --highlight-line {2} {1}'
