(in-package :stumpwm)
(ql:quickload :slynk)
(slynk:create-server :port 4004 :dont-close t)
;; (define-key *root-map* (kbd "[") "exchange-direction left")
(defparameter *terminal* "alacritty" "Stores the terminal emulator")
(defparameter *web-browser* "firefox" "Stores the web browser")
(run-shell-command "xmodmap -e 'clear mod4'" t)
(run-shell-command "xmodmap -e \'keycode 133 = F20\'" t)
(set-prefix-key (kbd "F20"))
(define-key *root-map* (kbd "W") (concatenate 'string "exec " *web-browser*)) 
(define-key *root-map* (kbd "c") (concatenate 'string "exec " *terminal*))
(if (not (head-mode-line (current-head)))
    (toggle-mode-line (current-screen) (current-head)))
(setf *window-format* "%m%n%s%c")
(setf *screen-mode-line-format* (list "[^B%n^b] %W^>%d"))
