[language.haskell]
filetypes = ["haskell"]
roots = ["Setup.hs", "stack.yaml", "*.cabal"]
command = "haskell-language-server-wrapper"
args = ["--lsp"]
formatTool = "fourmolu"
[language.dart]
filetypes = ["dart"]
roots = ["pubspec.yaml", ".git"]
command = "dart"
args = ["/opt/dart-sdk/bin/snapshots/analysis_server.dart.snapshot", "--lsp"]

